//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public struct Point
{
	public readonly int x;
	public readonly int y;

	public Point(int x, int y)
	{
				this.x = x;
				this.y = y;
	}
}


