//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Road : Placeable
{
	// Use this for initialization
	public override void Start (){
		Debug.Log ("Road Start");
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}


